name = "PowerNetworkModeling"
uuid = "9e052817-6d02-48d2-a14c-d9a445c7d635"
authors = ["Juan Luis Barberia"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
